/// Parsed contents of the QR code generated by `cpp-senior-design`.
///
/// Current format (see `cpp-senior-design/src/ui_main.cpp`):
/// `liftelligence://pair?host=<host>&port=<port>&token=<token>`
class PairingPayload {
  const PairingPayload({
    required this.host,
    required this.port,
    required this.token,
  });

  final String host;
  final int port;
  final String token;

  static PairingPayload? tryParse(String raw) {
    final t = raw.trim();
    if (t.isEmpty) return null;

    final uri = Uri.tryParse(t);
    if (uri == null) return null;

    // Accept both `liftelligence://pair?...` and a more typical path variant
    // like `liftelligence://host/pair?...` if we ever change the generator.
    final isLiftelligence = uri.scheme.toLowerCase() == 'liftelligence';
    if (!isLiftelligence) return null;

    final host = uri.queryParameters['host'];
    final portStr = uri.queryParameters['port'];
    final token = uri.queryParameters['token'];

    if (host == null || host.isEmpty) return null;
    if (portStr == null || portStr.isEmpty) return null;
    if (token == null || token.isEmpty) return null;

    final port = int.tryParse(portStr);
    if (port == null || port < 1 || port > 65535) return null;

    return PairingPayload(host: host, port: port, token: token);
  }

  String maskedToken({int keep = 4}) {
    final t = token;
    if (t.length <= keep) return t;
    return '${t.substring(0, keep)}…';
  }
}

