/// Parsed contents of the QR code generated by `cpp-senior-design`.
///
/// Format: `liftelligence://pair?nfc_id=<uid_hex>&token=<token>`
///
/// Server host/port are no longer embedded in the QR; they come from
/// `lib/config/server_config.dart` instead.
class PairingPayload {
  const PairingPayload({
    required this.nfcId,
    required this.token,
  });

  final String nfcId;
  final String token;

  static PairingPayload? tryParse(String raw) {
    final t = raw.trim();
    if (t.isEmpty) return null;

    final uri = Uri.tryParse(t);
    if (uri == null) return null;

    final isLiftelligence = uri.scheme.toLowerCase() == 'liftelligence';
    if (!isLiftelligence) return null;

    final nfcId = uri.queryParameters['nfc_id'];
    final token = uri.queryParameters['token'];

    if (nfcId == null || nfcId.isEmpty) return null;
    if (token == null || token.isEmpty) return null;

    return PairingPayload(nfcId: nfcId, token: token);
  }

  String maskedToken({int keep = 4}) {
    final t = token;
    if (t.length <= keep) return t;
    return '${t.substring(0, keep)}…';
  }

  String maskedNfcId({int keep = 8}) {
    if (nfcId.length <= keep) return nfcId.toUpperCase();
    return '${nfcId.substring(0, keep).toUpperCase()}…';
  }
}
